name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les dépendances
        run: npm ci

      - name: Linter Angular
        run: npm run lint

      - name: Vérification formatage Prettier
        run: npm run format-check

  lint-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Installer les dépendances
        run: composer install

      - name: Linter PHP PSR-12
        run: ./vendor/bin/phpcs .

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Vérifier le build Docker
        run: docker compose build